# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Description:
#   Realm is a lightweight, event-based library

licenses([])

exports_files([])

cc_library(
    name = "realm",
    hdrs = [
      "realm.h",
      "realm/activemsg.h",
      "realm/activemsg.inl",
      "realm/atomics.h",
      "realm/atomics.inl",
      "realm/bgwork.h",
      "realm/bytearray.h",
      "realm/bytearray.inl",
      "realm/caching_allocator.h",
      "realm/circ_queue.h",
      "realm/circ_queue.inl",
      "realm/cmdline.h",
      "realm/cmdline.inl",
      "realm/codedesc.h",
      "realm/codedesc.inl",
      "realm/compiler_support.h",
      "realm/cuda/cuda_access.h",
      "realm/cuda/cuda_access.inl",
      "realm/cuda/cuda_internal.h",
      "realm/cuda/cuda_memcpy.h",
      "realm/cuda/cuda_module.h",
      "realm/cuda/cuda_module.inl",
      "realm/cuda/cuda_redop.h",
      "realm/cuda/cudart_hijack.h",
      "realm/custom_serdez.h",
      "realm/custom_serdez.inl",
      "realm/deppart/byfield.h",
      "realm/deppart/deppart_config.h",
      "realm/deppart/image.h",
      "realm/deppart/inst_helper.h",
      "realm/deppart/partitions.h",
      "realm/deppart/partitions.inl",
      "realm/deppart/preimage.h",
      "realm/deppart/rectlist.h",
      "realm/deppart/rectlist.inl",
      "realm/deppart/setops.h",
      "realm/deppart/sparsity_impl.h",
      "realm/deppart/sparsity_impl.inl",
      "realm/dynamic_table.h",
      "realm/dynamic_table.inl",
      "realm/dynamic_templates.h",
      "realm/dynamic_templates.inl",
      "realm/event.h",
      "realm/event.inl",
      "realm/event_impl.h",
      "realm/event_impl.inl",
      "realm/faults.h",
      "realm/id.h",
      "realm/id.inl",
      "realm/idx_impl.h",
      "realm/indexspace.h",
      "realm/indexspace.inl",
      "realm/inst_impl.h",
      "realm/inst_layout.h",
      "realm/inst_layout.inl",
      "realm/instance.h",
      "realm/instance.inl",
      "realm/interval_tree.h",
      "realm/interval_tree.inl",
      "realm/kokkos_interop.h",
      "realm/lists.h",
      "realm/lists.inl",
      "realm/llvmjit/llvmjit.h",
      "realm/llvmjit/llvmjit.inl",
      "realm/llvmjit/llvmjit_internal.h",
      "realm/llvmjit/llvmjit_module.h",
      "realm/logging.h",
      "realm/logging.inl",
      "realm/machine.h",
      "realm/machine.inl",
      "realm/machine_impl.h",
      "realm/mem_impl.h",
      "realm/mem_impl.inl",
      "realm/memory.h",
      "realm/metadata.h",
      "realm/module.h",
      "realm/module_config.h",
      "realm/module_config.inl",
      "realm/mpi/am_mpi.h",
      "realm/mpi/mpi_module.h",
      "realm/mutex.h",
      "realm/mutex.inl",
      "realm/network.h",
      "realm/network.inl",
      "realm/nodeset.h",
      "realm/nodeset.inl",
      "realm/numa/numa_module.h",
      "realm/numa/numasysif.h",
      "realm/nvtx.h",
      "realm/openmp/openmp_internal.h",
      "realm/openmp/openmp_module.h",
      "realm/openmp/openmp_threadpool.h",
      "realm/openmp/openmp_threadpool.inl",
      "realm/operation.h",
      "realm/operation.inl",
      "realm/point.h",
      "realm/point.inl",
      "realm/pri_queue.h",
      "realm/pri_queue.inl",
      "realm/proc_impl.h",
      "realm/processor.h",
      "realm/processor.inl",
      "realm/procset/procset_module.h",
      "realm/profiling.h",
      "realm/profiling.inl",
      "realm/python/python_internal.h",
      "realm/python/python_module.h",
      "realm/python/python_source.h",
      "realm/python/python_source.inl",
      "realm/realm_c.h",
      "realm/realm_config.h",
      "realm/redop.h",
      "realm/repl_heap.h",
      "realm/reservation.h",
      "realm/reservation.inl",
      "realm/rsrv_impl.h",
      "realm/runtime.h",
      "realm/runtime_impl.h",
      "realm/sampling.h",
      "realm/sampling.inl",
      "realm/sampling_impl.h",
      "realm/serialize.h",
      "realm/serialize.inl",
      "realm/shm.h",
      "realm/sparsity.h",
      "realm/sparsity.inl",
      "realm/subgraph.h",
      "realm/subgraph.inl",
      "realm/subgraph_impl.h",
      "realm/tasks.h",
      "realm/threads.h",
      "realm/threads.inl",
      "realm/timers.h",
      "realm/timers.inl",
      "realm/transfer/address_list.h",
      "realm/transfer/channel.h",
      "realm/transfer/channel.inl",
      "realm/transfer/channel_disk.h",
      "realm/transfer/ib_memory.h",
      "realm/transfer/lowlevel_dma.h",
      "realm/transfer/transfer.h",
      "realm/transfer/transfer.inl",
      "realm/transfer/transfer_utils.h",
      "realm/transfer/transfer_utils.inl",
      "realm/ucx/bootstrap/bootstrap.h",
      "realm/ucx/bootstrap/bootstrap_internal.h",
      "realm/ucx/bootstrap/bootstrap_loader.h",
      "realm/ucx/bootstrap/bootstrap_util.h",
      "realm/ucx/mpool.h",
      "realm/ucx/spinlock.h",
      "realm/ucx/ucp_context.h",
      "realm/ucx/ucp_dyn_load.h",
      "realm/ucx/ucp_internal.h",
      "realm/ucx/ucp_module.h",
      "realm/ucx/ucp_utils.h",
      "realm/utils.h",
      "realm/utils.inl",
      "realm_defines.h",
    ],
    visibility = ["//visibility:public"],
)
